### ISSUE TITLE
Add support for HTTP headers configuration

### ISSUE THREAD

**Issue by antoine-mulet** [open-rpc/inspector#172]
It would be great to be able to set some HTTP headers on a per request basis. It would useful for APIs using Bearer authentication for example.

[GraphQL Playground](https://github.com/prisma-labs/graphql-playground) supports it in a rather simple but effective way for example.

**Comment by su45fg** [comment]
I get start http.

**Comment by su45fg** [comment]
[suriya](https://join.skype.com/invite/iz5rewCeJSBR) #177

**Comment by antoine-mulet** [comment]
@su45fg not sure to understand you comment.

@openrpc-bastion any thoughts about supporting HTTP headers? I had a look at the code the other day and it would require supporting user defined headers in https://github.com/open-rpc/client-js/blob/master/src/transports/HTTPTransport.ts. It seems that there is no support for transport specific capabilities at the moment so I understand that it would require changing a bit the design and maybe the spirit of this tool? I would gladly give it a go to see what it could be like but my front-end dev skills are pretty limited so it may be a bit too advanced for me.

**Comment by shanejonas** [comment]
> It seems that there is no support for transport specific capabilities at the moment so I understand that it would require changing a bit the design and maybe the spirit of this tool?

We just added postmessage `window` and `iframe` to client-js, which needs to get added to this tool. They will need some transport specific capabilities in the future, like what size to open the postmessage window, so I **do** think we need to handle extra options per transport. HTTP headers could be an option for the HTTP transport.

**Comment by antoine-mulet** [comment]
Thanks @shanejonas, it makes sense!

**Comment by antoine-mulet** [comment]
Hi @shanejonas, I came here to check the status of this issue and realized that you merged some code in the client-js repo a while ago. So I had a look at recent changes in the inspector repo and found #237. I just pulled and tried it and this is exactly what I had in mind, which is great! Is there any reason why this issue is still open?

**Comment by shanejonas** [comment]
@antoine-mulet was waiting until the inspector had a UI to add headers, which was added recently. closing now
